# DO NOT CHANGE the "init" and "install" sections below

image: Visual Studio 2015

environment:
  NOT_CRAN: true
  USE_RTOOLS: true
  R_VERSION: 3.5.2
  PATH: "%PATH%;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0;C:\\MinGW\\msys\\1.0\\bin"
  matrix:
    - PYTHON_VERSION: "3.6"
      MINICONDA: C:\Miniconda36-x64
      PLATFORM: x64

#    - PYTHON: "C:\\Python36"
#      RETICULATE_PYTHON: "C:\\Python36"

matrix:
  fast_finish: true

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

# Adapt as necessary starting from here
install:
  ps: Bootstrap

build_script:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create --name spacy_condaenv python=3.6.8"
  # - "%PYTHON%\\python.exe -m pip install setuptools spacy"
  # - "%PYTHON%\\python.exe -m spacy download en"
  - activate spacy_condaenv 
  - conda install -c conda-forge spacy 
  - python -m spacy download en
  - conda deactivate
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
